package bonilladesande.pl2_bonilla_desande_23_24.GUI;

import bonilladesande.pl2_bonilla_desande_23_24.*;

import javax.swing.ImageIcon;

public class BotonAnfitriones extends javax.swing.JPanel {
    
    /*CONSTRUCTOR BÁSICO QUE NECESITA DEL PARÁMETRO "ANFITRIÓN" PARA MOSTRAR EN LA MINIATURA.*/
    Anfitrion anfitrion; 
    public BotonAnfitriones(Anfitrion anfitrion) {    
        this.anfitrion = anfitrion;
        initComponents();
        myInitComponents(anfitrion);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombreInmuebleAlojamientoBoton = new javax.swing.JLabel();
        valoracionAlojamientoBoton = new javax.swing.JLabel();
        fotoBotonAlojamientoLabel = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        nombreInmuebleAlojamientoBoton.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        nombreInmuebleAlojamientoBoton.setText("Nombre del anfitrion");

        valoracionAlojamientoBoton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        valoracionAlojamientoBoton.setText("Valoración");

        fotoBotonAlojamientoLabel.setText("FOTO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fotoBotonAlojamientoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(valoracionAlojamientoBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(nombreInmuebleAlojamientoBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 108, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(nombreInmuebleAlojamientoBoton, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(valoracionAlojamientoBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fotoBotonAlojamientoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents



    /*EN TÉRMINOS DE INTERFAZ GRÁFICA, ESTE CÓDIGO ES EL QUE SE OCUPA DE PONER LAS MINIATURAS DE LOS ANFITRIONES,
    LOS CUALES PODRÁ VER EL ADMINISTRADOR. SE OCUPA DE COGER EL NOMBRE DE UN ANFITRIÓN YA INSERTADO Y SU FOTO DE
    PERFIL, DE ESTA MANERA PODRÁ OFRECER UNA VISTA PREVIA AL ADMINISTRADOR DEL USUARIO EN CUESTIÓN.*/
    public void myInitComponents(Anfitrion anfitrion) {
        nombreInmuebleAlojamientoBoton.setText(anfitrion.getNombre());
        //valoracionAlojamientoBoton.setText(String.valueOf(anfitrion.getCalificacion()));    
        ImageIcon imagen = new ImageIcon(anfitrion.getFoto());
        ImageIcon imgRedimensionada = new ImageIcon(imagen.getImage().getScaledInstance(166, 109, 1));
        fotoBotonAlojamientoLabel.setIcon(imgRedimensionada);
    }



     /*AL PULSAR SOBRE UNO DE LOS ANFITRIONES, SE CAMBIA LA PÁGINA A UNA VENTANA MÁS AMPLIA DONDE SE PUEDEN VER
    EN DETALLE LOS DATOS DEL ANFITRIÓN.*/
    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        
        GestorVentanas.gestorVentanas.paginaVerAnfitrion = new VerAnfitrion(anfitrion);
        GestorVentanas.gestorVentanas.ventanaJavaBNB.frameJavaBNB.setViewportView(GestorVentanas.gestorVentanas.paginaVerAnfitrion);
        GestorVentanas.gestorVentanas.ventanaJavaBNB.setVisible(true);
        
    }//GEN-LAST:event_formMouseClicked
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel fotoBotonAlojamientoLabel;
    private javax.swing.JLabel nombreInmuebleAlojamientoBoton;
    private javax.swing.JLabel valoracionAlojamientoBoton;
    // End of variables declaration//GEN-END:variables
}
