/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bonilladesande.pl2_bonilla_desande_23_24.GUI;

import bonilladesande.pl2_bonilla_desande_23_24.BaseDatos;
import bonilladesande.pl2_bonilla_desande_23_24.BibliotecaExcepciones;
import bonilladesande.pl2_bonilla_desande_23_24.DatosInmueble;
import bonilladesande.pl2_bonilla_desande_23_24.Direccion;
import bonilladesande.pl2_bonilla_desande_23_24.FiltraImagenes;
import bonilladesande.pl2_bonilla_desande_23_24.Inmueble;
import bonilladesande.pl2_bonilla_desande_23_24.TextPrompt;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Miguel
 */
public class EditarDatosInmueble extends javax.swing.JFrame {

    
    private String rutaImagen = BaseDatos.inmuebleSeleccionado.getRutaFoto(), extension = "jpg";
    String[] rutafoto = rutaImagen.split("/");
    String nombreImagen = rutafoto[5];
    private File file;
    private BufferedImage bimage;
    /**
     * Creates new form EditarDatosInmueble
     */
    public EditarDatosInmueble() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        TextPrompt placenombreinmueble = new TextPrompt(BaseDatos.inmuebleSeleccionado.getTitulo(), NombreAlojamiento);
        TextPrompt placedescripcion = new TextPrompt(BaseDatos.inmuebleSeleccionado.getDescripcion(), DescripcionAlojamiento);
        TextPrompt placeservicios = new TextPrompt(BaseDatos.inmuebleSeleccionado.getServicios(), ServiciosAlojamiento);
        TextPrompt placecalle = new TextPrompt(BaseDatos.inmuebleSeleccionado.getDireccion().getCalle(), calleField);
        TextPrompt placenumero = new TextPrompt(String.valueOf(BaseDatos.inmuebleSeleccionado.getDireccion().getNumero()), numeroField);
        TextPrompt placecp = new TextPrompt(String.valueOf(BaseDatos.inmuebleSeleccionado.getDireccion().getCodigoPostal()), cpField);
        TextPrompt placeciudad = new TextPrompt(BaseDatos.inmuebleSeleccionado.getDireccion().getCiudad(), ciudadField);
        TextPrompt placebanios = new TextPrompt(String.valueOf(BaseDatos.inmuebleSeleccionado.getDatos().getBaños()), baniosField);
        TextPrompt placehuespedes = new TextPrompt(String.valueOf(BaseDatos.inmuebleSeleccionado.getDatos().getHuespedes()), huespedesField);
        TextPrompt placecamas = new TextPrompt(String.valueOf(BaseDatos.inmuebleSeleccionado.getDatos().getCamas()), camasField);
        TextPrompt placehabitaciones = new TextPrompt(String.valueOf(BaseDatos.inmuebleSeleccionado.getDatos().getHabitaciones()), habitacionesField);
        TextPrompt placeprecionoche = new TextPrompt(String.valueOf(BaseDatos.inmuebleSeleccionado.getPrecioNoche()), precioNocheField);
        
        if(BaseDatos.inmuebleSeleccionado.esCasa()){
            Casa.setEnabled(true);
        }
        else{
            Apartamento.setEnabled(true);
        }
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        casa_apartamento = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        Apartamento = new javax.swing.JRadioButton();
        Casa = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        SubirAlojamiento = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        calleField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        numeroField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cpField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        ciudadField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        calle = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        CancelarSubida = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        baniosField = new javax.swing.JTextField();
        ServiciosAlojamiento = new javax.swing.JTextField();
        huespedesField = new javax.swing.JTextField();
        DescripcionAlojamiento = new javax.swing.JTextField();
        camasField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        habitacionesField = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        FotoAloja = new javax.swing.JLabel();
        precioNocheField = new javax.swing.JTextField();
        SubirFotoAlojamiento = new javax.swing.JButton();
        NombreAlojamiento = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        SubirAlojamiento1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Título del Alojamiento:");

        casa_apartamento.add(Apartamento);
        Apartamento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Apartamento.setText("Apartamento");
        Apartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApartamentoActionPerformed(evt);
            }
        });

        casa_apartamento.add(Casa);
        Casa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Casa.setText("Casa");
        Casa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CasaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Fotografía");

        SubirAlojamiento.setText("Actualizar");
        SubirAlojamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubirAlojamientoActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Baños:");
        jLabel8.setToolTipText("");

        calleField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calleFieldActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Número:");
        jLabel9.setToolTipText("");

        numeroField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroFieldActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Código postal:");
        jLabel10.setToolTipText("");

        cpField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpFieldActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("Ciudad:");
        jLabel11.setToolTipText("");

        ciudadField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ciudadFieldActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("Datos del inmueble");
        jLabel12.setToolTipText("");

        calle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        calle.setText("Calle:");
        calle.setToolTipText("");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setText("Huéspedes:");
        jLabel14.setToolTipText("");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setText("Camas:");
        jLabel15.setToolTipText("");

        CancelarSubida.setText("Cancelar");
        CancelarSubida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarSubidaActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setText("Habitaciones:");
        jLabel16.setToolTipText("");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Descripción");
        jLabel6.setToolTipText("");

        baniosField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baniosFieldActionPerformed(evt);
            }
        });

        ServiciosAlojamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ServiciosAlojamientoActionPerformed(evt);
            }
        });

        huespedesField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                huespedesFieldActionPerformed(evt);
            }
        });

        DescripcionAlojamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DescripcionAlojamientoActionPerformed(evt);
            }
        });

        camasField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                camasFieldActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Servicios");

        habitacionesField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                habitacionesFieldActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel17.setText("Precio Noche:");
        jLabel17.setToolTipText("");

        precioNocheField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precioNocheFieldActionPerformed(evt);
            }
        });

        SubirFotoAlojamiento.setText("Subir Foto Alojamiento");
        SubirFotoAlojamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubirFotoAlojamientoActionPerformed(evt);
            }
        });

        NombreAlojamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreAlojamientoActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Dirección");
        jLabel7.setToolTipText("");

        SubirAlojamiento1.setText("Borrar Alojamiento");
        SubirAlojamiento1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubirAlojamiento1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(780, Short.MAX_VALUE)
                .addComponent(SubirAlojamiento1)
                .addGap(38, 38, 38))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(45, 45, 45)
                            .addComponent(jLabel6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(115, 115, 115)
                                    .addComponent(jLabel4))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(59, 59, 59)
                                    .addComponent(ServiciosAlojamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(calleField, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel11)
                                        .addComponent(ciudadField, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel9)
                                                .addComponent(jLabel10))
                                            .addGap(24, 24, 24)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(numeroField)
                                                .addComponent(cpField, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(69, 69, 69)
                                            .addComponent(jLabel7)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(79, 79, 79)
                                            .addComponent(jLabel12))
                                        .addGroup(layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(0, 81, Short.MAX_VALUE)
                                                    .addComponent(SubirAlojamiento)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(CancelarSubida))
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                    .addComponent(jLabel14)
                                                    .addGap(36, 36, 36)
                                                    .addComponent(huespedesField))
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                    .addComponent(jLabel8)
                                                    .addGap(76, 76, 76)
                                                    .addComponent(baniosField))
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel15)
                                                        .addComponent(jLabel16))
                                                    .addGap(24, 24, 24)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(camasField)
                                                        .addComponent(habitacionesField)))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel17)
                                                    .addGap(22, 22, 22)
                                                    .addComponent(precioNocheField)))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addComponent(calle)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(DescripcionAlojamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(19, 19, 19)
                                            .addComponent(SubirFotoAlojamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(38, 38, 38)
                                            .addComponent(jLabel3)))
                                    .addGap(18, 18, 18)
                                    .addComponent(FotoAloja, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(Casa)
                                    .addGap(18, 18, 18)
                                    .addComponent(Apartamento))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(18, 18, 18)
                                    .addComponent(NombreAlojamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addGap(11, 11, 11)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(SubirAlojamiento1)
                .addContainerGap(384, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(28, 28, 28)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(NombreAlojamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(31, 31, 31)
                            .addComponent(calle)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel8)
                                        .addComponent(baniosField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(19, 19, 19)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel14)
                                        .addComponent(huespedesField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel15)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel16))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(22, 22, 22)
                                            .addComponent(camasField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(habitacionesField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel17)
                                        .addComponent(precioNocheField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(37, 37, 37)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(SubirAlojamiento)
                                        .addComponent(CancelarSubida)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(calleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(numeroField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel9))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cpField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel10))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel11)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(ciudadField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(33, 33, 33)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(Casa)
                                                .addComponent(Apartamento)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(21, 21, 21)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(36, 36, 36)
                                            .addComponent(SubirFotoAlojamiento)))
                                    .addGap(29, 29, 29))))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(39, 39, 39)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ServiciosAlojamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(DescripcionAlojamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FotoAloja, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(21, 21, 21)))
                    .addGap(28, 28, 28)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /** 
     * @param evt
     */
    private void ApartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApartamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ApartamentoActionPerformed

    
    /** 
     * @param evt
     */
    private void CasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CasaActionPerformed

    }//GEN-LAST:event_CasaActionPerformed

    
    /** 
     * @param evt
     */
    private void SubirAlojamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubirAlojamientoActionPerformed
        try {
            if ("".equals(NombreAlojamiento.getText()) || "".equals(DescripcionAlojamiento.getText()) || "".equals(ServiciosAlojamiento.getText()) || "".equals(calleField.getText()) || "".equals(numeroField.getText()) || "".equals(cpField.getText()) || "".equals(ciudadField.getText()) || "".equals(baniosField.getText()) || "".equals(camasField.getText()) || "".equals(habitacionesField.getText()) || "".equals(huespedesField.getText())){
                throw new BibliotecaExcepciones.CamposVacios("Rellena todos los campos. (Se debe resubir la imagen)");
            }
            String ruta = "./src/main/java/imagenes/" + nombreImagen;
            bimage = ImageIO.read(file);
            File fout = new File(ruta);
            ImageIO.write(bimage, extension, fout);

            String alojamiento = NombreAlojamiento.getText();
            String descripcion = DescripcionAlojamiento.getText();
            String serviciosalojamiento = ServiciosAlojamiento.getText();
            String calle = calleField.getText();
            int numero = Integer.parseInt(numeroField.getText());
            int cp = Integer.parseInt(cpField.getText());
            String ciudad = ciudadField.getText();
            int banios = Integer.parseInt(baniosField.getText());
            int camas = Integer.parseInt(camasField.getText());
            int habitaciones = Integer.parseInt(habitacionesField.getText());
            int huespedes = Integer.parseInt(huespedesField.getText());

            if (alojamiento.isEmpty() || descripcion.isEmpty() || serviciosalojamiento.isEmpty()) {
                throw new BibliotecaExcepciones.CamposVacios("Todos los campos deben estar llenos.");
            }
            if (!Casa.isSelected() && !Apartamento.isSelected()) {
                throw new BibliotecaExcepciones.BotonesSinSeleccionar("Debes elegir si es una casa o un apartamento.");
            }

            DatosInmueble datos = new DatosInmueble(huespedes, habitaciones, camas, banios);
            Direccion direccion = new Direccion(calle, numero, cp, ciudad);
            Inmueble inmueble = new Inmueble(alojamiento, direccion, datos, Casa.isEnabled(), Integer.parseInt(precioNocheField.getText()), serviciosalojamiento, ruta, descripcion, BaseDatos.anfitriones.get(BaseDatos.user.getPosicionArrayList()));
            
            for(int i = 0; i < BaseDatos.reservas.size(); i++){
                if(BaseDatos.reservas.get(i).getInmueble().getTitulo().equals(BaseDatos.inmuebleSeleccionado.getTitulo())){
                    BaseDatos.reservas.get(i).setInmueble(inmueble);
                }
            }
            
            for(int i = 0; i < BaseDatos.inmuebles.size(); i++){
                if(BaseDatos.inmuebles.get(i).getAnfitrion().getCorreo().equals(BaseDatos.inmuebleSeleccionado.getAnfitrion().getCorreo()) && BaseDatos.inmuebles.get(i).getTitulo().equals(BaseDatos.inmuebleSeleccionado.getTitulo())){
                    BaseDatos.inmuebles.set(i, inmueble);
                }
            }
            
            BaseDatos.inmuebleSeleccionado = null;
            

            GestorVentanas.cambioVentana("SubirAlojamiento", "PaginaPrincipal");

            JOptionPane.showMessageDialog(this, "Alojamiento subido con éxito.");
        } catch (BibliotecaExcepciones.CamposVacios
            | BibliotecaExcepciones.BotonesSinSeleccionar e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            //AlojamientoLiada.setText("Por favor, revise todos los campos e inténtelo de nuevo.");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error al subir el alojamiento.");
            //AlojamientoLiada.setText("Por favor, revise todos los campos e inténtelo de nuevo.");
        }

    }//GEN-LAST:event_SubirAlojamientoActionPerformed

    
    /** 
     * @param evt)GestorVentanas.cambioVentana("EditarDatosInmueble"
     * @param JFileChooser.APPROVE_OPTION
     */
    private void calleFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calleFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calleFieldActionPerformed

    
    /** 
     * @param evt)GestorVentanas.cambioVentana("EditarDatosInmueble"
     * @param JFileChooser.APPROVE_OPTION
     */
    private void numeroFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroFieldActionPerformed

    
    /** 
     * @param evt)GestorVentanas.cambioVentana("EditarDatosInmueble"
     * @param JFileChooser.APPROVE_OPTION
     */
    private void cpFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpFieldActionPerformed

    
    /** 
     * @param evt)GestorVentanas.cambioVentana("EditarDatosInmueble"
     * @param JFileChooser.APPROVE_OPTION
     */
    private void ciudadFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ciudadFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ciudadFieldActionPerformed

    
    /** 
     * @param evt)GestorVentanas.cambioVentana("EditarDatosInmueble"
     * @param JFileChooser.APPROVE_OPTION
     */
    private void CancelarSubidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarSubidaActionPerformed
        // TODO add your handling code here:
        GestorVentanas.cambioVentana("EditarDatosInmueble", "PaginaAlojamiento");
    }//GEN-LAST:event_CancelarSubidaActionPerformed

    
    /** 
     * @param JFileChooser.APPROVE_OPTION
     */
    private void baniosFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baniosFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_baniosFieldActionPerformed

    
    /** 
     * @param JFileChooser.APPROVE_OPTION
     */
    private void ServiciosAlojamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ServiciosAlojamientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ServiciosAlojamientoActionPerformed

    
    /** 
     * @param JFileChooser.APPROVE_OPTION
     */
    private void huespedesFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_huespedesFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_huespedesFieldActionPerformed

    
    /** 
     * @param JFileChooser.APPROVE_OPTION
     */
    private void DescripcionAlojamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescripcionAlojamientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DescripcionAlojamientoActionPerformed

    
    /** 
     * @param JFileChooser.APPROVE_OPTION
     */
    private void camasFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_camasFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_camasFieldActionPerformed

    
    /** 
     * @param JFileChooser.APPROVE_OPTION
     */
    private void habitacionesFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_habitacionesFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_habitacionesFieldActionPerformed

    
    /** 
     * @param JFileChooser.APPROVE_OPTION
     */
    private void precioNocheFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precioNocheFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precioNocheFieldActionPerformed

    
    /** 
     * @param JFileChooser.APPROVE_OPTION
     */
    private void SubirFotoAlojamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubirFotoAlojamientoActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.addChoosableFileFilter(new FiltraImagenes());
        fileChooser.setAcceptAllFileFilterUsed(false);

        int option = fileChooser.showOpenDialog(this);
        if (option == JFileChooser.APPROVE_OPTION) {
            file = fileChooser.getSelectedFile();
            rutaImagen = file.getAbsolutePath();
            nombreImagen = file.getName();
            System.out.println("imagen: " + nombreImagen);
            String[] aux = nombreImagen.split("\\.");
        } else {
            JOptionPane.showMessageDialog(this, "Ningún fichero seleccionado", "Mensaje", JOptionPane.ERROR_MESSAGE);
        }
        ImageIcon imagen = new ImageIcon(rutaImagen);
        //Se redimensiona
        ImageIcon imgRedimensionada = new ImageIcon(imagen.getImage().getScaledInstance(FotoAloja.getWidth(), FotoAloja.getHeight(), 1));
        FotoAloja.setIcon(imgRedimensionada);
    }//GEN-LAST:event_SubirFotoAlojamientoActionPerformed

    
    /** 
     * @param JOptionPane.showConfirmDialog(this
     * @param inmueble?"
     * @param "Confirmar"
     * @param JOptionPane.YES_NO_OPTION
     * @param JOptionPane.YES_OPTION
     */
    private void NombreAlojamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreAlojamientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreAlojamientoActionPerformed

    
    /** 
     * @param JOptionPane.showConfirmDialog(this
     * @param inmueble?"
     * @param "Confirmar"
     * @param JOptionPane.YES_NO_OPTION
     * @param JOptionPane.YES_OPTION
     */
    private void SubirAlojamiento1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubirAlojamiento1ActionPerformed
        int response = JOptionPane.showConfirmDialog(
                this, 
                "¿Desea eliminar el inmueble?", 
                "Confirmar",
                JOptionPane.YES_NO_OPTION, 
                JOptionPane.QUESTION_MESSAGE);

                //SI EL USUARIO RESPONDE QUE QUIERE SER ELIMINADO, SE RETIRARÁ SU INFORMACIÓN DE LA BASE DE DATOS.
                if (response == JOptionPane.YES_OPTION) {
                    BaseDatos.inmuebles.remove(BaseDatos.inmuebleSeleccionado);
                    if(BaseDatos.user.getTipo() == 0){
                        GestorVentanas.cambioVentana("PaginaAlojamiento", "PaginaAdministrador");
                    }
                    else{
                        GestorVentanas.cambioVentana("PaginaAlojamiento", "PaginaPrincipal");
                    }
                }  
                else if (response == JOptionPane.NO_OPTION) {
                    
                
            } 
    }//GEN-LAST:event_SubirAlojamiento1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarDatosInmueble.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarDatosInmueble.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarDatosInmueble.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarDatosInmueble.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarDatosInmueble().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Apartamento;
    private javax.swing.JButton CancelarSubida;
    public javax.swing.JRadioButton Casa;
    private javax.swing.JTextField DescripcionAlojamiento;
    public javax.swing.JLabel FotoAloja;
    private javax.swing.JTextField NombreAlojamiento;
    private javax.swing.JTextField ServiciosAlojamiento;
    private javax.swing.JButton SubirAlojamiento;
    private javax.swing.JButton SubirAlojamiento1;
    private javax.swing.JButton SubirFotoAlojamiento;
    public javax.swing.JTextField baniosField;
    private javax.swing.JLabel calle;
    public javax.swing.JTextField calleField;
    public javax.swing.JTextField camasField;
    private javax.swing.ButtonGroup casa_apartamento;
    public javax.swing.JTextField ciudadField;
    public javax.swing.JTextField cpField;
    public javax.swing.JTextField habitacionesField;
    public javax.swing.JTextField huespedesField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JTextField numeroField;
    public javax.swing.JTextField precioNocheField;
    // End of variables declaration//GEN-END:variables
}
