package bonilladesande.pl2_bonilla_desande_23_24.GUI;

import bonilladesande.pl2_bonilla_desande_23_24.BaseDatos;
import bonilladesande.pl2_bonilla_desande_23_24.BibliotecaExcepciones;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.time.LocalDate;
import javax.swing.JOptionPane;

public class JavaBNB extends javax.swing.JFrame {

    public JavaBNB() {
        initComponents();    
        
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                //LLAMA A LA FUNCIÓN DE GUARDAR DATOS ANTES DE CERRAR UNA VENTANA
                BaseDatos.guardarDatosAnfitriones(BaseDatos.anfitriones);
                BaseDatos.guardarDatosInmuebles(BaseDatos.inmuebles);
                BaseDatos.guardarDatosParticulares(BaseDatos.particulares);
                BaseDatos.guardarDatosReservas(BaseDatos.reservas);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        tituloLabelPaginaPrincipal = new javax.swing.JLabel();
        frameJavaBNB = new javax.swing.JScrollPane();
        usuarioJavaBNBboton = new javax.swing.JButton();
        fotoLabelJavaBNB = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        busquedaCiudad = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        busquedaEntrada = new javax.swing.JTextField();
        busquedaSalida = new javax.swing.JTextField();
        buscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tituloLabelPaginaPrincipal.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        tituloLabelPaginaPrincipal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloLabelPaginaPrincipal.setText("JavaBNB");
        tituloLabelPaginaPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tituloLabelPaginaPrincipalMouseClicked(evt);
            }
        });

        frameJavaBNB.setBorder(null);
        frameJavaBNB.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        frameJavaBNB.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        usuarioJavaBNBboton.setText("Usuario");
        usuarioJavaBNBboton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioJavaBNBbotonActionPerformed(evt);
            }
        });

        fotoLabelJavaBNB.setText("FOTO");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Ciudad:");

        busquedaCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busquedaCiudadActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Fecha entrada:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Fecha salida:");

        busquedaEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busquedaEntradaActionPerformed(evt);
            }
        });

        busquedaSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busquedaSalidaActionPerformed(evt);
            }
        });

        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(tituloLabelPaginaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(20, 20, 20)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(busquedaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(busquedaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(busquedaCiudad))
                .addGap(29, 29, 29)
                .addComponent(buscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(usuarioJavaBNBboton, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fotoLabelJavaBNB, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(frameJavaBNB, javax.swing.GroupLayout.DEFAULT_SIZE, 973, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tituloLabelPaginaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(usuarioJavaBNBboton, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                            .addComponent(buscar))
                        .addComponent(fotoLabelJavaBNB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(busquedaCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(busquedaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3))
                            .addComponent(busquedaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(frameJavaBNB, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //SI SE PULSA EL BOTÓN DE USUARIO, REDIRIGE AL USUARIO A LA PÁGINA DE AJUSTES DE USUARIO
    private void usuarioJavaBNBbotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioJavaBNBbotonActionPerformed

        GestorVentanas.cambioVentana("JavaBNB", "AjustesUsuario");
    }//GEN-LAST:event_usuarioJavaBNBbotonActionPerformed
    //SI SE TOCA EL LABEL DE LA PÁGINA PRINCIPAL, LLEVA AL USUARIO A LA PÁGINA PRINCIPAL
    private void tituloLabelPaginaPrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tituloLabelPaginaPrincipalMouseClicked
      
        GestorVentanas.cambioVentana("", "PaginaPrincipal");
    }//GEN-LAST:event_tituloLabelPaginaPrincipalMouseClicked

    private void busquedaCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busquedaCiudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_busquedaCiudadActionPerformed

    private void busquedaEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busquedaEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_busquedaEntradaActionPerformed

    private void busquedaSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busquedaSalidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_busquedaSalidaActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        try{
            String ciudad = busquedaCiudad.getText();
            String entrada = busquedaEntrada.getText();
            String salida = busquedaSalida.getText();
            
            if((entrada.isEmpty() && !salida.isEmpty()) || (!entrada.isEmpty() && salida.isEmpty()) || ((!entrada.isEmpty() && !salida.isEmpty() && "".equals(ciudad) )) ){
                throw new BibliotecaExcepciones.CamposVacios("Si filtras por fecha, debes rellenar la entrada, la salida y la ciudad.");
            }

            if ("".equals(ciudad) && "".equals(entrada) && "".equals(salida)){
                GestorVentanas.cambioVentana("PaginaPrincipal", "PaginaPrincipal");
            }
            else {
            
                LocalDate fechaEntrada;
                LocalDate fechaSalida;
                
                if (!"".equals(ciudad) && "".equals(entrada) && "".equals(salida)){
                    fechaEntrada = LocalDate.of(2100, 01, 01);
                    fechaSalida = LocalDate.of(2100, 01, 02);


                }

                else{
                    String[] entradaSplit = entrada.split("/");
                    String[] salidaSplit = salida.split("/");

                    fechaEntrada = LocalDate.of(Integer.parseInt(entradaSplit[2]), Integer.parseInt(entradaSplit[1]), Integer.parseInt(entradaSplit[0]));
                    fechaSalida = LocalDate.of(Integer.parseInt(salidaSplit[2]), Integer.parseInt(salidaSplit[1]), Integer.parseInt(salidaSplit[0]));

                    if (fechaEntrada.isAfter(fechaSalida)){
                        throw new BibliotecaExcepciones.FechaFinMenorInicio("No puedes poner la fecha de salida menor a la de entrada");
                    }
                }

                GestorVentanas.gestorVentanas.ciudad = ciudad;
                GestorVentanas.gestorVentanas.fechaEntrada = fechaEntrada;
                GestorVentanas.gestorVentanas.fechaSalida = fechaSalida;

                GestorVentanas.cambioVentana("PaginaPrincipal", "PaginaPrincipalFiltrada");

                GestorVentanas.gestorVentanas.ciudad = null;
                GestorVentanas.gestorVentanas.fechaEntrada = null;
                GestorVentanas.gestorVentanas.fechaSalida = null;
                
            }
        }
        catch (BibliotecaExcepciones.CamposVacios | BibliotecaExcepciones.FechaFinMenorInicio e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_buscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JavaBNB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JavaBNB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JavaBNB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JavaBNB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JavaBNB().setVisible(true);
            }
        });    
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton buscar;
    public javax.swing.JTextField busquedaCiudad;
    public javax.swing.JTextField busquedaEntrada;
    public javax.swing.JTextField busquedaSalida;
    private javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JLabel fotoLabelJavaBNB;
    public javax.swing.JScrollPane frameJavaBNB;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel tituloLabelPaginaPrincipal;
    public javax.swing.JButton usuarioJavaBNBboton;
    // End of variables declaration//GEN-END:variables
}
