package bonilladesande.pl2_bonilla_desande_23_24.GUI;

public class ListaAlojamientos extends javax.swing.JPanel {

    public ListaAlojamientos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        alojamientoBoton1 = new bonilladesande.pl2_bonilla_desande_23_24.GUI.AlojamientoBoton();
        alojamientoBoton2 = new bonilladesande.pl2_bonilla_desande_23_24.GUI.AlojamientoBoton();
        alojamientoBoton3 = new bonilladesande.pl2_bonilla_desande_23_24.GUI.AlojamientoBoton();
        alojamientoBoton4 = new bonilladesande.pl2_bonilla_desande_23_24.GUI.AlojamientoBoton();
        alojamientoBoton5 = new bonilladesande.pl2_bonilla_desande_23_24.GUI.AlojamientoBoton();

        alojamientoBoton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                alojamientoBoton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alojamientoBoton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(alojamientoBoton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(alojamientoBoton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(alojamientoBoton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(alojamientoBoton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(alojamientoBoton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(alojamientoBoton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(alojamientoBoton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(alojamientoBoton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(alojamientoBoton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(386, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void alojamientoBoton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alojamientoBoton1MouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_alojamientoBoton1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private bonilladesande.pl2_bonilla_desande_23_24.GUI.AlojamientoBoton alojamientoBoton1;
    private bonilladesande.pl2_bonilla_desande_23_24.GUI.AlojamientoBoton alojamientoBoton2;
    private bonilladesande.pl2_bonilla_desande_23_24.GUI.AlojamientoBoton alojamientoBoton3;
    private bonilladesande.pl2_bonilla_desande_23_24.GUI.AlojamientoBoton alojamientoBoton4;
    private bonilladesande.pl2_bonilla_desande_23_24.GUI.AlojamientoBoton alojamientoBoton5;
    // End of variables declaration//GEN-END:variables
}
