/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package bonilladesande.pl2_bonilla_desande_23_24.GUI;

/**
 *
 * @author marco
 */
import bonilladesande.pl2_bonilla_desande_23_24.BibliotecaExcepciones;
import bonilladesande.pl2_bonilla_desande_23_24.FiltraImagenes;
import bonilladesande.pl2_bonilla_desande_23_24.TextPrompt;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

public class SubirAlojamiento extends javax.swing.JPanel {

    private String nombreImagen, rutaImagen, extension = "jpg";
    private File file;
    private BufferedImage bimage;

    /**
     * Creates new form SubirAlojamiento
     */
    public SubirAlojamiento() {
        initComponents();
        TextPrompt placenombreinmueble = new TextPrompt ("Introduce el nombre del inmueble", NombreAlojamiento);
        TextPrompt placenombreanfirtrion = new TextPrompt ("Introduce el nombre del anfitrion", AnfitrionAlojamiento);
        TextPrompt placedescripcion = new TextPrompt("Introduce una descripción para el alojamieneto", DescripcionAlojamiento);
        TextPrompt placeservicios = new TextPrompt("Introduce una descripción para el alojamieneto", ServiciosAlojamiento);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Apartamento = new javax.swing.JRadioButton();
        Casa = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        SubirAlojamiento = new javax.swing.JButton();
        CancelarSubida = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        ServiciosAlojamiento = new javax.swing.JTextField();
        DescripcionAlojamiento = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        AlojamientoLiada = new javax.swing.JLabel();
        FotoAloja = new javax.swing.JLabel();
        SubirFotoAlojamiento = new javax.swing.JButton();
        NombreAlojamiento = new javax.swing.JTextField();
        AnfitrionAlojamiento = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Título del Alojamiento:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Nombre del Anfitrión:");

        Apartamento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Apartamento.setText("Apartamento");
        Apartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApartamentoActionPerformed(evt);
            }
        });

        Casa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Casa.setText("Casa");
        Casa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CasaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Fotografía");

        SubirAlojamiento.setText("Subir Alojamiento");
        SubirAlojamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubirAlojamientoActionPerformed(evt);
            }
        });

        CancelarSubida.setText("Cancelar");
        CancelarSubida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarSubidaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Descripción");

        ServiciosAlojamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ServiciosAlojamientoActionPerformed(evt);
            }
        });

        DescripcionAlojamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DescripcionAlojamientoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Servicios");

        SubirFotoAlojamiento.setText("Subir Foto Alojamiento");
        SubirFotoAlojamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubirFotoAlojamientoActionPerformed(evt);
            }
        });

        NombreAlojamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreAlojamientoActionPerformed(evt);
            }
        });

        AnfitrionAlojamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnfitrionAlojamientoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(NombreAlojamiento, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                                    .addComponent(AnfitrionAlojamiento)))
                            .addComponent(AlojamientoLiada, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addComponent(SubirAlojamiento)
                                .addGap(18, 18, 18)
                                .addComponent(CancelarSubida))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(Casa)
                                .addGap(18, 18, 18)
                                .addComponent(Apartamento))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(FotoAloja, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(SubirFotoAlojamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ServiciosAlojamiento)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(DescripcionAlojamiento))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NombreAlojamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AnfitrionAlojamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Casa)
                        .addComponent(Apartamento)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(DescripcionAlojamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ServiciosAlojamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SubirAlojamiento)
                            .addComponent(CancelarSubida)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(FotoAloja, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SubirFotoAlojamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AlojamientoLiada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void DescripcionAlojamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescripcionAlojamientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DescripcionAlojamientoActionPerformed

    private void SubirAlojamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubirAlojamientoActionPerformed
        try {
            bimage = ImageIO.read(file);
            File fout = new File("./src/main/java/imagenes/" + nombreImagen);
            ImageIO.write(bimage, extension, fout);
            String alojamiento = NombreAlojamiento.getText();
            String anfitrion = AnfitrionAlojamiento.getText();
            String descripcion = DescripcionAlojamiento.getText();
            String serviciosalojamiento = ServiciosAlojamiento.getText();

            if (alojamiento.isEmpty() || anfitrion.isEmpty() || descripcion.isEmpty() || serviciosalojamiento.isEmpty()) {
                throw new BibliotecaExcepciones.CamposVacios("Todos los campos deben estar llenos.");
            }
            if (!Casa.isSelected() && !Apartamento.isSelected()) {
                throw new BibliotecaExcepciones.BotonesSinSeleccionar("Debes elegir si es una casa o un apartamento.");
            }
            JOptionPane.showMessageDialog(this, "Alojamiento subido con éxito.");
        } catch (BibliotecaExcepciones.CamposVacios e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            AlojamientoLiada.setText("Por favor, revise todos los campos e inténtelo de nuevo.");
        } catch (BibliotecaExcepciones.BotonesSinSeleccionar e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            AlojamientoLiada.setText("Por favor, revise todos los campos e inténtelo de nuevo.");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error al subir el alojamiento.");
            AlojamientoLiada.setText("Porfavor, revise todos los campos e inténtelo de nuevo.");
        }

    }//GEN-LAST:event_SubirAlojamientoActionPerformed

    private void CancelarSubidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarSubidaActionPerformed
        // TODO add your handling code here:
        GestorVentanas.cambioVentana("SubirAlojamiento", "PaginaPrincipal");
    }//GEN-LAST:event_CancelarSubidaActionPerformed

    private void SubirFotoAlojamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubirFotoAlojamientoActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.addChoosableFileFilter(new FiltraImagenes());
        fileChooser.setAcceptAllFileFilterUsed(false);

        int option = fileChooser.showOpenDialog(this);
        if (option == JFileChooser.APPROVE_OPTION) {
            file = fileChooser.getSelectedFile();
            rutaImagen = file.getAbsolutePath();
            nombreImagen = file.getName();
            System.out.println("imagen: " + nombreImagen);
            String[] aux = nombreImagen.split("\\.");
        } else {
            JOptionPane.showMessageDialog(this, "Ningún fichero seleccionado", "Mensaje", JOptionPane.ERROR_MESSAGE);
        }
        ImageIcon imagen = new ImageIcon(rutaImagen);
        //Se redimensiona
        ImageIcon imgRedimensionada = new ImageIcon(imagen.getImage().getScaledInstance(FotoAloja.getWidth(), FotoAloja.getHeight(), 1));
        FotoAloja.setIcon(imgRedimensionada);
    }//GEN-LAST:event_SubirFotoAlojamientoActionPerformed

    private void AnfitrionAlojamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnfitrionAlojamientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AnfitrionAlojamientoActionPerformed

    private void CasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CasaActionPerformed

    }//GEN-LAST:event_CasaActionPerformed

    private void ApartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApartamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ApartamentoActionPerformed

    private void NombreAlojamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreAlojamientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreAlojamientoActionPerformed

    private void ServiciosAlojamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ServiciosAlojamientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ServiciosAlojamientoActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AlojamientoLiada;
    private javax.swing.JTextField AnfitrionAlojamiento;
    private javax.swing.JRadioButton Apartamento;
    private javax.swing.JButton CancelarSubida;
    private javax.swing.JRadioButton Casa;
    private javax.swing.JTextField DescripcionAlojamiento;
    private javax.swing.JLabel FotoAloja;
    private javax.swing.JTextField NombreAlojamiento;
    private javax.swing.JTextField ServiciosAlojamiento;
    private javax.swing.JButton SubirAlojamiento;
    private javax.swing.JButton SubirFotoAlojamiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
