/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package bonilladesande.pl2_bonilla_desande_23_24.GUI;

/**
 *
 * @author marco
 */
import bonilladesande.pl2_bonilla_desande_23_24.BaseDatos;
import bonilladesande.pl2_bonilla_desande_23_24.BibliotecaExcepciones;
import bonilladesande.pl2_bonilla_desande_23_24.Direccion;
import bonilladesande.pl2_bonilla_desande_23_24.FiltraImagenes;
import bonilladesande.pl2_bonilla_desande_23_24.Inmueble;
import bonilladesande.pl2_bonilla_desande_23_24.DatosInmueble;
import bonilladesande.pl2_bonilla_desande_23_24.TextPrompt;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*PARA SUBIR UN ALOJAMIENTO, NECESITAMOS UNA RUTA DE IMAGEN, Y PARA ELLOS UTILIZAMOS VARIOS IMPORTS, COMO
EL IMPORT FILE O EL IMPORT BUFFERED IMAGE*/
public class SubirAlojamiento extends javax.swing.JPanel {

    private String nombreImagen, rutaImagen, extension = "jpg";
    private File file;
    private BufferedImage bimage;
    
    /**
     * Creates new form SubirAlojamiento
     */
    
    //CREAMOS PLACEHOLDERS PARA HACER EL PROCESO MÁS INTUITIVO.
    public SubirAlojamiento() {
        initComponents();
        TextPrompt placenombreinmueble = new TextPrompt("Introduce el nombre del inmueble.", NombreAlojamiento);
        TextPrompt placedescripcion = new TextPrompt("Introduce una descripción para el alojamieneto.", DescripcionAlojamiento);
        TextPrompt placeservicios = new TextPrompt("Introduce los servicios para el alojamieneto.", ServiciosAlojamiento);
        TextPrompt placecalle = new TextPrompt("Introduce el nombre de la calle.", calleField);
        TextPrompt placenumerocalle = new TextPrompt("Nº Calle", calleField);
        TextPrompt placepostal = new TextPrompt("XXXXX", calleField);
        TextPrompt placeciudad = new TextPrompt("Introduce el nombre de la ciudad.", ciudadField);
        TextPrompt placebaños = new TextPrompt("Nº Baños", baniosField);
        TextPrompt placehuespedes = new TextPrompt("Nº Huespedes", huespedesField);
        TextPrompt placecamas = new TextPrompt("Nº Camas", camasField);
        TextPrompt placehabitaciones = new TextPrompt("Nº Habitaciones", habitacionesField);
        TextPrompt placenoches = new TextPrompt("Precio por noche.", precioNocheField);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        casa_apartamento = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        Apartamento = new javax.swing.JRadioButton();
        Casa = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        SubirAlojamiento = new javax.swing.JButton();
        CancelarSubida = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        DescripcionAlojamiento = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        AlojamientoLiada = new javax.swing.JLabel();
        FotoAloja = new javax.swing.JLabel();
        SubirFotoAlojamiento = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        calleField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        numeroField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cpField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        ciudadField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        calle = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        baniosField = new javax.swing.JTextField();
        huespedesField = new javax.swing.JTextField();
        camasField = new javax.swing.JTextField();
        habitacionesField = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        precioNocheField = new javax.swing.JTextField();
        ServiciosAlojamiento = new javax.swing.JTextField();
        NombreAlojamiento = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Título del Alojamiento:");

        casa_apartamento.add(Apartamento);
        Apartamento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Apartamento.setText("Apartamento");
        Apartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApartamentoActionPerformed(evt);
            }
        });

        casa_apartamento.add(Casa);
        Casa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Casa.setText("Casa");
        Casa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CasaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Fotografía");

        SubirAlojamiento.setText("Subir Alojamiento");
        SubirAlojamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubirAlojamientoActionPerformed(evt);
            }
        });

        CancelarSubida.setText("Cancelar");
        CancelarSubida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarSubidaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Descripción");
        jLabel6.setToolTipText("");

        DescripcionAlojamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DescripcionAlojamientoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Servicios");

        SubirFotoAlojamiento.setText("Subir Foto Alojamiento");
        SubirFotoAlojamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubirFotoAlojamientoActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Dirección");
        jLabel7.setToolTipText("");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Baños:");
        jLabel8.setToolTipText("");

        calleField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calleFieldActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Número:");
        jLabel9.setToolTipText("");

        numeroField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroFieldActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Código postal:");
        jLabel10.setToolTipText("");

        cpField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpFieldActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("Ciudad:");
        jLabel11.setToolTipText("");

        ciudadField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ciudadFieldActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("Datos del inmueble");
        jLabel12.setToolTipText("");

        calle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        calle.setText("Calle:");
        calle.setToolTipText("");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setText("Huéspedes:");
        jLabel14.setToolTipText("");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setText("Camas:");
        jLabel15.setToolTipText("");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setText("Habitaciones:");
        jLabel16.setToolTipText("");

        baniosField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baniosFieldActionPerformed(evt);
            }
        });

        huespedesField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                huespedesFieldActionPerformed(evt);
            }
        });

        camasField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                camasFieldActionPerformed(evt);
            }
        });

        habitacionesField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                habitacionesFieldActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel17.setText("Precio Noche:");
        jLabel17.setToolTipText("");

        precioNocheField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precioNocheFieldActionPerformed(evt);
            }
        });

        ServiciosAlojamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ServiciosAlojamientoActionPerformed(evt);
            }
        });

        NombreAlojamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreAlojamientoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(115, 115, 115)
                        .addComponent(jLabel4)
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(calleField, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11)
                                    .addComponent(ciudadField, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel10))
                                        .addGap(24, 24, 24)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(numeroField)
                                            .addComponent(cpField, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(69, 69, 69)
                                        .addComponent(jLabel7)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(79, 79, 79)
                                        .addComponent(jLabel12))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(SubirAlojamiento)
                                                .addGap(18, 18, 18)
                                                .addComponent(CancelarSubida))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(jLabel14)
                                                .addGap(36, 36, 36)
                                                .addComponent(huespedesField))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addGap(76, 76, 76)
                                                .addComponent(baniosField))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel15)
                                                    .addComponent(jLabel16))
                                                .addGap(24, 24, 24)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(camasField)
                                                    .addComponent(habitacionesField)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel17)
                                                .addGap(22, 22, 22)
                                                .addComponent(precioNocheField)))
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(calle)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(NombreAlojamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DescripcionAlojamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(SubirFotoAlojamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addComponent(jLabel3)))
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addComponent(ServiciosAlojamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(FotoAloja, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Casa)
                                .addGap(18, 18, 18)
                                .addComponent(Apartamento)))
                        .addContainerGap(19, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NombreAlojamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel12)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ServiciosAlojamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DescripcionAlojamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(FotoAloja, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(calle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(calleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(numeroField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cpField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ciudadField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(33, 33, 33)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(Casa)
                                            .addComponent(Apartamento)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(36, 36, 36)
                                        .addComponent(SubirFotoAlojamiento))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(baniosField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(huespedesField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel15)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel16))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(camasField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(habitacionesField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17)
                                    .addComponent(precioNocheField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(SubirAlojamiento)
                                    .addComponent(CancelarSubida)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(calleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(numeroField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cpField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ciudadField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(33, 33, 33)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(Casa)
                                            .addComponent(Apartamento)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(36, 36, 36)
                                        .addComponent(SubirFotoAlojamiento)))
                                .addGap(53, 53, 53)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addComponent(AlojamientoLiada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    //EN ESTE ESPACIO, EL ANFITRIÓN PUEDE ESCRIBIR UNA DESCRIPCIÓN SOBRE EL APARTAMENTO QUE VA A SUBIR.
    private void DescripcionAlojamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescripcionAlojamientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DescripcionAlojamientoActionPerformed
    /*AL PRESIONAR EL BOTÓN DE SUBIR ALOJAMIENTO, OCURREN UNA SERIE DE COSAS: EN PRIMER LUGAR, SE CONSIGUE LA
    FOTO DE PERFIL SUBIDA DEL APARTAMENTO. LUEGO SE OBTIENE EL NOMBRE DEL ALOJAMIENTO, SU DESCRIPCIÓN, SUS SERVICIOS,
    SU CALLE (Y SU NÚMERO DE CALLE), SU CÓDIGO POSTAL, SU CIUDAD, SU NÚMERO DE BAÑOS, SU NÚMERO DE CAMAS, SU NÚMERO DE
    HABITACIONES Y SU NÚMERO DE HUÉSPEDES.*/
    private void SubirAlojamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubirAlojamientoActionPerformed
        try {
            String ruta = "./src/main/java/imagenes/" + nombreImagen;
            bimage = ImageIO.read(file);
            File fout = new File(ruta);
            ImageIO.write(bimage, extension, fout);

            String alojamiento = NombreAlojamiento.getText();
            String descripcion = DescripcionAlojamiento.getText();
            String serviciosalojamiento = ServiciosAlojamiento.getText();
            String calle = calleField.getText();
            int numero = Integer.parseInt(numeroField.getText());
            int cp = Integer.parseInt(cpField.getText());
            String ciudad = ciudadField.getText();
            int banios = Integer.parseInt(baniosField.getText());
            int camas = Integer.parseInt(camasField.getText());
            int habitaciones = Integer.parseInt(habitacionesField.getText());
            int huespedes = Integer.parseInt(huespedesField.getText());
            //SI ALGUNO DE LOS CAMPOS ESTÁ VACÍO, TIRA UN ERROR.
            if (alojamiento.isEmpty() || descripcion.isEmpty() || serviciosalojamiento.isEmpty()) {
                throw new BibliotecaExcepciones.CamposVacios("Todos los campos deben estar llenos.");
            }
            int digitospostal = String.valueOf(cp).length();
            //SI EL CÓDIGO POSTAL NO TIENE CINCO DÍGITOS, TIRA UN ERROR.
            if (digitospostal != 5){
                 throw new BibliotecaExcepciones.PostalEscacharrado("El código postal debe de contener exactamente 5 dígitos");
            }
            //SI NI APARTAMENTO NI CASA ESTÁ SELECCIONADO, TIRA OTRO ERROR.
            if (!Casa.isSelected() && !Apartamento.isSelected()) {
                throw new BibliotecaExcepciones.BotonesSinSeleccionar("Debes elegir si es una casa o un apartamento.");
            }
            //CREA UN NUEVO INMUEBLE CON LOS DATOS OBTENIDOS Y LO SUBE AL ARRAY DE LA BASE DE DATOS.
            DatosInmueble datos = new DatosInmueble(huespedes, habitaciones, camas, banios);
            Direccion direccion = new Direccion(calle, numero, cp, ciudad);
            Inmueble inmueble = new Inmueble(alojamiento, direccion, datos, Casa.isEnabled(), Integer.parseInt(precioNocheField.getText()), serviciosalojamiento, ruta, descripcion, BaseDatos.anfitriones.get(BaseDatos.user.getPosicionArrayList()));
            BaseDatos.inmuebles.add(inmueble);
            
            //UNA VEZ SUBIDO, CAMBIA LA VENTANA A LA PÁGINA PRINCIPAL.
            GestorVentanas.cambioVentana("SubirAlojamiento", "PaginaPrincipal");

            //TE IMPRIME UN MENSAJE PARA COMUNICARTE QUE EL APARTAMENTO SE HA PUBLICADO EXITOSAMENTE.
            JOptionPane.showMessageDialog(this, "Alojamiento subido con éxito.");
        }catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Alguno de los formatos numéricos es erróneo.");
                AlojamientoLiada.setText("Por favor, revise todos los campos e inténtelo de nuevo.");
            }  
        catch (BibliotecaExcepciones.CamposVacios
                | BibliotecaExcepciones.BotonesSinSeleccionar 
                | BibliotecaExcepciones.PostalEscacharrado e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            AlojamientoLiada.setText("Por favor, revise todos los campos e inténtelo de nuevo.");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error al subir el alojamiento.");
            AlojamientoLiada.setText("Por favor, revise todos los campos e inténtelo de nuevo.");
        }


    }//GEN-LAST:event_SubirAlojamientoActionPerformed

    private void CancelarSubidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarSubidaActionPerformed
        // TODO add your handling code here:
        GestorVentanas.cambioVentana("SubirAlojamiento", "PaginaPrincipal");
    }//GEN-LAST:event_CancelarSubidaActionPerformed

    private void SubirFotoAlojamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubirFotoAlojamientoActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.addChoosableFileFilter(new FiltraImagenes());
        fileChooser.setAcceptAllFileFilterUsed(false);

        int option = fileChooser.showOpenDialog(this);
        if (option == JFileChooser.APPROVE_OPTION) {
            file = fileChooser.getSelectedFile();
            rutaImagen = file.getAbsolutePath();
            nombreImagen = file.getName();
            System.out.println("imagen: " + nombreImagen);
            String[] aux = nombreImagen.split("\\.");
        } else {
            JOptionPane.showMessageDialog(this, "Ningún fichero seleccionado", "Mensaje", JOptionPane.ERROR_MESSAGE);
        }
        ImageIcon imagen = new ImageIcon(rutaImagen);
        //Se redimensiona
        ImageIcon imgRedimensionada = new ImageIcon(imagen.getImage().getScaledInstance(FotoAloja.getWidth(), FotoAloja.getHeight(), 1));
        FotoAloja.setIcon(imgRedimensionada);

    }//GEN-LAST:event_SubirFotoAlojamientoActionPerformed

    private void CasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CasaActionPerformed

    }//GEN-LAST:event_CasaActionPerformed

    private void ApartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApartamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ApartamentoActionPerformed

    private void calleFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calleFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calleFieldActionPerformed

    private void ciudadFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ciudadFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ciudadFieldActionPerformed

    private void numeroFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroFieldActionPerformed

    private void cpFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpFieldActionPerformed

    private void baniosFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baniosFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_baniosFieldActionPerformed

    private void huespedesFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_huespedesFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_huespedesFieldActionPerformed

    private void camasFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_camasFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_camasFieldActionPerformed

    private void habitacionesFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_habitacionesFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_habitacionesFieldActionPerformed

    private void precioNocheFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precioNocheFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precioNocheFieldActionPerformed

    private void ServiciosAlojamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ServiciosAlojamientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ServiciosAlojamientoActionPerformed

    private void NombreAlojamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreAlojamientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreAlojamientoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AlojamientoLiada;
    private javax.swing.JRadioButton Apartamento;
    private javax.swing.JButton CancelarSubida;
    public javax.swing.JRadioButton Casa;
    private javax.swing.JTextField DescripcionAlojamiento;
    public javax.swing.JLabel FotoAloja;
    private javax.swing.JTextField NombreAlojamiento;
    private javax.swing.JTextField ServiciosAlojamiento;
    private javax.swing.JButton SubirAlojamiento;
    private javax.swing.JButton SubirFotoAlojamiento;
    public javax.swing.JTextField baniosField;
    private javax.swing.JLabel calle;
    public javax.swing.JTextField calleField;
    public javax.swing.JTextField camasField;
    private javax.swing.ButtonGroup casa_apartamento;
    public javax.swing.JTextField ciudadField;
    public javax.swing.JTextField cpField;
    public javax.swing.JTextField habitacionesField;
    public javax.swing.JTextField huespedesField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JTextField numeroField;
    public javax.swing.JTextField precioNocheField;
    // End of variables declaration//GEN-END:variables
}
