/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bonilladesande.pl2_bonilla_desande_23_24.GUI;

import bonilladesande.pl2_bonilla_desande_23_24.BaseDatos;
import bonilladesande.pl2_bonilla_desande_23_24.FiltraImagenes;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author marco
 */
/*PARA SUBIR UNA FOTO DE PERFIL, NECESITAMOS UNA RUTA DE IMAGEN, Y PARA ELLOS UTILIZAMOS VARIOS IMPORTS, COMO
EL IMPORT FILE O EL IMPORT BUFFERED IMAGE*/
public class SubirFoto extends javax.swing.JFrame {

    private String nombreImagen, rutaImagen, extension = "jpg";
    private File file;
    private BufferedImage bimage;

    /**
     * Creates new form SubirFoto
     */
    public SubirFoto() {
        initComponents();
        myInitComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GuardaCambios = new javax.swing.JButton();
        Volver = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        BotonSubirFoto = new javax.swing.JButton();
        FotoActual = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        GuardaCambios.setText("Aplicar cambios");
        GuardaCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardaCambiosActionPerformed(evt);
            }
        });

        Volver.setText("Cancelar");
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });

        BotonSubirFoto.setText("Subir nueva foto de perfil");
        BotonSubirFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSubirFotoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BotonSubirFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(GuardaCambios)
                        .addGap(31, 31, 31)
                        .addComponent(Volver))
                    .addComponent(FotoActual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(BotonSubirFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(FotoActual, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GuardaCambios)
                    .addComponent(Volver)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /** 
     * @param JFileChooser.APPROVE_OPTION
     */
    /*AL PULSAR EL BOTÓN DE SUBIR NUEVA FOTO DE PERFIL, EMPLEA EL "add.ChoosableFileFilter", LO QUE
    REGULA QUE SOLO SE PUEDAN ELEGIR FOTOS DE DETERMINADOS ARCHIVOS. DESPUÉS, TE DEJA SELECCIONAR UNA FOTO 
    DE LA RUTA QUE ELIJAS, CONSIGUE EL NOMBRE DE LA IMAGEN, Y LA IMPRIME.*/
    private void BotonSubirFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSubirFotoActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.addChoosableFileFilter(new FiltraImagenes());
        fileChooser.setAcceptAllFileFilterUsed(false);
        
        int option = fileChooser.showOpenDialog(this);
        if (option == JFileChooser.APPROVE_OPTION) {
            file = fileChooser.getSelectedFile();
            rutaImagen = file.getAbsolutePath();
            nombreImagen = file.getName();
            System.out.println("imagen: " + nombreImagen);
            String[] aux = nombreImagen.split("\\.");
        } 
        //EN CASO CONTRARIO, TE DIRÁ QUE NO HAY NINGÚN FICHERO SELECCIONADO.
        else {
            JOptionPane.showMessageDialog(this, "Ningún fichero seleccionado", "Mensaje", JOptionPane.ERROR_MESSAGE);
        }
        ImageIcon imagen = new ImageIcon(rutaImagen);
        ImageIcon imgRedimensionada = new ImageIcon(imagen.getImage().getScaledInstance(FotoActual.getWidth(), FotoActual.getHeight(), 1));
        FotoActual.setIcon(imgRedimensionada);
    }//GEN-LAST:event_BotonSubirFotoActionPerformed
    
    /** 
     * @param evt
     */
    /*CUANDO GUARDAS LOS CAMBIOS, BUSCA EN EL PAQUETE DE IMÁGENES DEL MISMO PROGRAMA POR EL NOMBRE DE LA IMAGEN,
    LA COLOCA EN LA POSICIÓN DE FOTO DE PERFIL DE USUARIO, Y TE IMPRIME UN PANEL EN EL QUE TE CONFIRMA QUE SE 
    PUDO GUARDAR O QUE HUBO UN ERROR AL GUARDARLA.*/
    private void GuardaCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardaCambiosActionPerformed
       
        try {
            bimage = ImageIO.read(file);
            File fout = new File("./src/main/java/imagenes/" + nombreImagen);
            ImageIO.write(bimage, extension, fout);
            JOptionPane.showMessageDialog(this, "Imagen guardada");
            
            //DEPENDIENDO DE SI EL USUARIO ES UN PARTICULAR O UN ANFITRIÓN, SE OPERARÁ DE UNA MANERA O DE OTRA.
                if (BaseDatos.user.getTipo() == 1){
                BaseDatos.particulares.get(BaseDatos.user.getPosicionArrayList()).setFoto("./src/main/java/imagenes/" + nombreImagen);
            }
            else{
                BaseDatos.anfitriones.get(BaseDatos.user.getPosicionArrayList()).setFoto("./src/main/java/imagenes/" + nombreImagen);
            }
            GestorVentanas.cambioVentana("SubirFoto", "AjustesUsuario");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error al guardar imagen");
        }
    }//GEN-LAST:event_GuardaCambiosActionPerformed
    
    /** 
     * @param evt)GestorVentanas.cambioVentana("SubirFoto"
     * @param myInitComponents(
     */
    //SI SE PRESIONA EL BOTÓN DE VOLVER, CIERRA LA PESTAÑA DE SUBIR FOTO Y TE HACE VOLVER A LOS AJUSTES DE USUARIO.
    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        GestorVentanas.cambioVentana("SubirFoto", "AjustesUsuario");
    }//GEN-LAST:event_VolverActionPerformed

    //ESTE MÉTODO ESTÁ PARA QUE AL CERRAR LA PESTAÑA DE SUBIR FOTO NO SE CIERRE TODA LA APLICACIÓN. 
    private void myInitComponents(){
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SubirFoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SubirFoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SubirFoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SubirFoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SubirFoto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonSubirFoto;
    private javax.swing.JLabel FotoActual;
    private javax.swing.JButton GuardaCambios;
    private javax.swing.JButton Volver;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
